wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.7
    is_jupyter_run: true
    is_kaggle_kernel: true
    python_version: 3.7.12
    session_history: code/_session_history.ipynb
    start_time: 1641403140
    t:
      3:
      - 2
      - 13
      - 16
      4: 3.7.12
      5: 0.12.7
      8:
      - 1
      - 2
      - 5
    visualize:
      annotations:
        panel_config:
          fieldSettings:
            value: Number of Annotations
          panelDefId: wandb/histogram/v0
          stringSettings:
            title: Distribution for Number of Annotations per Frame
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: annotations_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
      frames:
        panel_config:
          fieldSettings:
            label: Video ID
            value: ' '
          panelDefId: wandb/bar/v0
          stringSettings:
            title: -Frequency of Frames per Video-
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: frames_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
      frames2:
        panel_config:
          fieldSettings:
            label: Sequence ID
            value: ' '
          panelDefId: wandb/bar/v0
          stringSettings:
            title: -Frequency of Frames per Sequence-
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: frames2_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
_wandb_kernel:
  desc: null
  value: aot
competition:
  desc: null
  value: greatReef
